import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "React-Three-Fiber App",
  description: "Generated by create next app & react-three-fiber",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
